### ISSUE TITLE
Make API development platform independent

### ISSUE THREAD

**Issue by djrenren** [rit-sse/api#10]
We shouldn't rely on shell scripts like bootstrap/init_storage.sh I think that's the only one at this point but yeah let's not go down that road

**Comment by kristenmills** [comment]
There is one in slushy too.

**Comment by craigcabrey** [comment]
Don't have a machine to test on, so I'd say PR a replacement script that is platform agnostic.

**Comment by djrenren** [comment]
@craigcabrey I will submit a PR but I'm just gonna throw this out there, you don't need windows to not use a shell script :P
