### ISSUE TITLE
Events Root Endpoint Functionality

### ISSUE THREAD

**Issue by kristenmills** [rit-sse/api#13]
### Default fields
* `name`
* `start_date`
* `end_date`
* `description`
* `location`
* `short_name`
* `short description`
* `image`
* `featured`
* `recurrence` - We'll deal with this later...add it to the model but don't worry about it being anything other than null or empty string

[Occurrences Events Model](https://github.com/rit-sse/occurrences/blob/master/models/event.js) might help as a reference for proper validations.  

### Additional Fields
* `committee/group`

### Filters
* `start_date`
* `end_date`
* `when` (past, future, all)
* `limit`

**Comment by craigcabrey** [comment]
Need deets

**Comment by kristenmills** [comment]
Coming your way! Sorry I forgot I didn't fill this one out.
