### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by djrenren** [rit-sse/api#17]
A quick overview of what we need out of our authentication and authorization stack:

## Authentication:
- Multiple sources asserting they've authorized a user
    - Slack
    - Google Apps
- Varying levels of authority on user data (we trust Google Apps to populate first and last name more than slack)

#### Group-based authorization
Group-based auth is not role-based auth. There is a finite set of groups of which you can be a member.

Authorization will center around is the user a member of [x]

#### Varying levels of trust per authentication source
Slack should be considered less secure than Google Apps auth and our system should reflect it. There are two ways to do this:
- Make group membership contingent upon the level of trust we have in your authentication source. (i.e. I cannot act as a primary officers unless I auth with google apps)
- Make each authorization check decide if they want to restrict to auth source trust levels

#### Shared-secret preauthorization
1. Sign into slack _(authorized)_
2. Slack (slushy) requests a session token for the authorized user using the shared secret to encrypt the request or passing it over the wire. _(shared secret)_
3. The api server issues a session token (JSON web token) that identifies the user id and their auth source

#### RIT Google Apps
Still need to invesetigate if oauth will work when shibboleth is standing in the middle... I *think* so. If that's the case see google oauth docs. Sidenote: OAuth is a piece of shit

**Comment by kristenmills** [comment]
You could SAML instead for RIT.

**Comment by craigcabrey** [comment]
Since we aren't going with the federated system, I say we just auth against RIT.

For now, I can implement a dummy auth driver so that I can update the controllers with auth middleware, until I can get setup with Shibboleth.

[Relevent Laravel docs](http://laravel.com/docs/master/authentication#adding-custom-authentication-drivers).

**Comment by djrenren** [comment]
We still need federated auth if we want slushy to do anything that requires
permissions. We're just ditching the separate server idea
