### ISSUE TITLE
Officers Fields & Filters

### ISSUE THREAD

**Issue by kristenmills** [rit-sse/api#19]
### Default fields
* `title`
* `position`

### Additional Fields
* `member`
* `term`

### Filters
* `positon`
* `member`
* `term`

**Comment by mok4ry** [comment]
### Additional Fields
* `email` (e.g. `"president@sse.se.rit.edu"`)

**Comment by kristenmills** [comment]
Do we store the full email?  I think it equates to `[position]@sse.se.rit.edu`

**Comment by craigcabrey** [comment]
`Email` can be a dynamic property for convenience.

**Comment by kristenmills** [comment]
:+1:

**Comment by craigcabrey** [comment]
(position is a dynamic attribute, so adding filter by `title` instead -- it'll be case-insensitive)
