### ISSUE TITLE
Tasks Root Endpoint Functionality

### ISSUE THREAD

**Issue by kocsenc** [rit-sse/api#28]
Task:
* `name`
* `description`
* `completed` (Boolean)
* `creator` (`Member`)
* `assignee` (`Member`)

Endpoints:
* `GET /tasks`
  * Filters: `creator, assignee, state`
* `POST /tasks`
  * Roles: `member`
* `GET /tasks/{id}`
* `PUT /tasks/{id}`
  * Roles: `member`
* `DELETE /tasks/{id}`
  * Roles: `officer`

**Comment by bbesmanoff** [comment]
So, is this just a centralized/persisted [todo app](http://todomvc.com/)?

**Comment by djrenren** [comment]
This seems like not useful...
