### ISSUE TITLE
Members of a committee should be under the members endpoint

### ISSUE THREAD

**Issue by kristenmills** [rit-sse/api#6]
I think it makes mores sense to do  `/members?committee={id}` as opposed to `committees\{id}\members`. I don't like nested resources especially when they are already at the top level anyway.  I bet @weswigham has some things to say about this as well.

**Comment by djrenren** [comment]
+1

**Comment by weswigham** [comment]
Filter>subresource. Since members are globally unique, they should be global - subresources should not point to a resource available elsewhere, as it breaks the paradigm that each resource has a single unique path it can be accessed from.

So yeah, `/members?committee={id}`
