### ISSUE TITLE
Agenda Items should be associated with an committee

### ISSUE THREAD

**Issue by kristenmills** [rit-sse/api#8]
Since in officer meeting, we group agenda items but by committee,  they should not only have a member association so we know who added but a committee association so it can be organized.

**Comment by craigcabrey** [comment]
:+1:

**Comment by craigcabrey** [comment]
Currently, I have two fields:

* `created_by` (Member)
* `updated_by` (Member)

We can change it to the following:

* `owner` (Committee)
* `updated_by` (Member of Committee)

**Comment by djrenren** [comment]
I'd like to have some form of convention for fields that reference a user and fields that reference a committee.
