### ISSUE TITLE
Rename Committees Endpoint

### ISSUE THREAD

**Issue by kristenmills** [rit-sse/api#9]
I've referred to this sort of data as "Committees" for far too long when in all actuality it is a just a title for a group of memberships, events, and/or probably agenda items as I suggested in #8.  I would say the committees are actually just a subset of the data that this endpoint will actually be used for.  

Just some examples of non-committees we've had in the past:
Freshman connection and Officers are examples of "Committees" in Scoreboard.
General is an example of a "Committee" in WTF.
President, VP, Treasurer, and Secretary will be "Committees" for agenda items

**Comment by craigcabrey** [comment]
Rename to `/groups`?

**Comment by kristenmills** [comment]
Yeah that works for me.
